USE [NewtonCompDB]
GO

/****** Object:  Table [dbo].[Skola_Kurs]    Script Date: 2015-06-14 20:26:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Skola_Kurs](
	[SkolNr] [char](20) NOT NULL,
	[KursId] [char](20) NOT NULL,
	[Skola_KursId] [char](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SkolNr] ASC,
	[KursId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Skola_Kurs]  WITH CHECK ADD FOREIGN KEY([KursId])
REFERENCES [dbo].[Kurs] ([KursId])
GO

ALTER TABLE [dbo].[Skola_Kurs]  WITH CHECK ADD FOREIGN KEY([SkolNr])
REFERENCES [dbo].[Skola] ([SkolNr])
GO


