USE [NewtonCompDB]
GO

/****** Object:  Table [dbo].[Elev_Kurs]    Script Date: 2015-06-14 20:25:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Elev_Kurs](
	[ElevId] [char](20) NOT NULL,
	[KursId] [char](20) NOT NULL,
	[Elev_KursNr] [char](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ElevId] ASC,
	[KursId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Elev_Kurs]  WITH CHECK ADD FOREIGN KEY([ElevId])
REFERENCES [dbo].[Elev] ([ElevId])
GO

ALTER TABLE [dbo].[Elev_Kurs]  WITH CHECK ADD FOREIGN KEY([KursId])
REFERENCES [dbo].[Kurs] ([KursId])
GO


