USE [NewtonCompDB]
GO

/****** Object:  Table [dbo].[Lektion]    Script Date: 2015-06-14 20:26:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Lektion](
	[LektionsNr] [char](20) NOT NULL,
	[Datum] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[LektionsNr] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


